version: '3'

services:
  web:
    container_name: node_app
    build: ./app
    volumes:
      - ./app:/app
    links:
      - mongo
    ports:
      - "8083:8080"
    
  mongo:
    container_name: node_db
    build: ./db
    volumes:
      - ./db/data:/data/db
      - ./db/scripts/:/scripts/
    ports:
      - "27017:27017"
    env_file:
      - ./db/mongo.env



